#!/bin/bash
sudo avr-gcc -g -Os -mmcu=atmega8 -c /home/pi/c/rgbfor_b/main.c
sudo avr-gcc -g -mmcu=atmega8 -o /home/pi/c/rgbfor_b/main.elf /home/pi/c/rgbfor_b/main.o
sudo avr-objcopy -j .text -j .data -O ihex /home/pi/c/rgbfor_b/main.elf /home/pi/c/rgbfor_b/main.hex

sudo avrdude -p m8 -c usbasp -e -U flash:w:/home/pi/c/rgbfor_b/main.hex
